# Generated by Django 3.0.8 on 2020-10-21 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('tipoUsuarioId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuarioId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('apellidoPaterno', models.CharField(max_length=250, verbose_name='ApellidoPaterno')),
                ('apellidoMaterno', models.CharField(max_length=250, verbose_name='ApellidoMaterno')),
                ('fechaNacimiento', models.DateField(verbose_name='FechaNacimiento')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=500, verbose_name='Password')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BodyIxchel_API.TipoUsuario')),
            ],
        ),
    ]
